##############################################
# This is a TOML UI Configuration for Rio/OS.
# Boom.
##############################################
title = "UI Configuration for Rio/OS"

## api host that nilavu will connect to
http_api = "http://localhost:9636"

## auth_server that nilavu will connect to
auth_server = "http://localhost:9636"

## watch_server is a host that the nilavu will connect to for real time triggers on
## update to resources.
watch_server = "https://localhost:7000"

## vnc server that we connect to using insecure mode.
## replace it to wss if we wish to connect via secure mode.
vnc_server = "ws://localhost:9000"

## count.ly url that provided by count.ly
countly_server = "http://countly.rioos.xyz"

##key that provided by count.ly
app_key = "9653325d8d0f5fe63c3491c93259bf4ff77821ca"
